package cc.ibooker.ibookereditorlib;

/**
 * 书客编辑器枚举类
 * Created by 邹峰立 on 2018/2/11.
 */
public class IbookerEditorEnum {
    public enum TOOLVIEW_TAG {
        IBTN_BOLD, IBTN_ITALIC, IBTN_STRIKEOUT, IBTN_UNDERLINE, IBTN_CAPITALS, IBTN_UPPERCASE, IBTN_LOWERCASE,
        IBTN_H1, IBTN_H2, IBTN_H3, IBTN_H4, IBTN_H5, IBTN_H6, IBTN_LINK, IBTN_QUOTE, IBTN_CODE, IBTN_IMG_U,
        IBTN_OL, IBTN_UL, IBTN_UNSELECTED, IBTN_SELECTED, IBTN_TABLE, IBTN_HTML, IBTN_HR, IBTN_EMOJI,
        IMG_BACK, IBTN_UNDO, IBTN_REDO, IBTN_EDIT, IBTN_PREVIEW, IBTN_HELP, IBTN_ABOUT, IBTN_SHARE, IBTN_ELSE,
        IBTN_SET
    }
}
